// <auto-generated />
using System;
using AntennaReader.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntennaReader.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518085424_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AntennaReader.Models.AntennaDiagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AntennaName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AntennaOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AntennaDiagrams");
                });

            modelBuilder.Entity("AntennaReader.Models.AntennaInterpolatedMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Angle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntennaDiagramId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DbValue")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AntennaDiagramId", "Angle")
                        .IsUnique();

                    b.ToTable("AntennaInterpolatedMeasurements");
                });

            modelBuilder.Entity("AntennaReader.Models.AntennaMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Angle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AntennaDiagramId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DbValue")
                        .HasColumnType("REAL");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AntennaDiagramId", "Angle")
                        .IsUnique();

                    b.ToTable("AntennaMeasurements");
                });

            modelBuilder.Entity("AntennaReader.Models.DrawingCanvasSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ContourStep")
                        .HasColumnType("REAL");

                    b.Property<int>("CsvExportPrecision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLogScale")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PATExportPrecision")
                        .HasColumnType("INTEGER");

                    b.Property<double>("lowerBound")
                        .HasColumnType("REAL");

                    b.Property<double>("upperBound")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DrawingCanvasSettings");
                });

            modelBuilder.Entity("AntennaReader.Models.AntennaInterpolatedMeasurement", b =>
                {
                    b.HasOne("AntennaReader.Models.AntennaDiagram", "Diagram")
                        .WithMany("InterpolatedMeasurements")
                        .HasForeignKey("AntennaDiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("AntennaReader.Models.AntennaMeasurement", b =>
                {
                    b.HasOne("AntennaReader.Models.AntennaDiagram", "Diagram")
                        .WithMany("Measurements")
                        .HasForeignKey("AntennaDiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("AntennaReader.Models.AntennaDiagram", b =>
                {
                    b.Navigation("InterpolatedMeasurements");

                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
